---
#- template:
#    src: config.xml
#    dest: /var/lib/jenkins/config.xml
#    owner: jenkins
#    group: jenkins
#    mode: 0644
#  notify:
#    - jenkins restart

#- lineinfile:
#    dest: /etc/nginx/sites-enabled/jenkins.conf
#    regexp: "#ARBITRARY_STUFF"
#    line: |
#      location ~ ^/(css|js|img|fonts)/ {
#        root /var/www/;
#      }
#  notify:
#    - nginx reload

- copy:
    src: SimpleTheme.cfg
    dest: /var/lib/jenkins/org.codefirst.SimpleThemeDecorator.xml
    owner: jenkins
    group: jenkins
    mode: 0644

- name: Ensure static assets exist
  file:
    path: /var/www/{{ item }}
    owner: www-data
    group: www-data
    state: directory
  with_items:
     - fonts
     - css
     - js
     - img

- copy:
    src: forge.{{ item }}
    dest: /var/www/{{ item }}/
  with_items:
    - js
    - css

- copy:
    src: "{{ item }}"
    dest: /var/www/img/
  with_items:
    - box.png
    - logo.png
    - search.png
    - Serrated_top.png
    - Serrated_bottom.png
    - FORGE_favicon.ico

- unarchive:
    src: "{{ item }}"
    dest: /var/www/fonts/
  with_items:
    - font-awesome-4.1.0.zip
#    - 170413.zip # Please see files/170413.zip.readme for more info

- unarchive:
    src: Drupal_cs.tgz
    dest: /usr/share/php/PHP/CodeSniffer/Standards/
    owner: root
    group: root
